# Generated by Django 3.2.3 on 2021-06-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Anonymous', max_length=50)),
                ('middle_name', models.CharField(default='Anonymous', max_length=50)),
                ('last_name', models.CharField(default='Anonymous', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, max_length=10, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('race', models.CharField(blank=True, max_length=20, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(default='Anonymous', max_length=500)),
                ('city', models.CharField(default='Anonymous', max_length=50)),
                ('state', models.CharField(default='Anonymous', max_length=50)),
                ('zipcode', models.CharField(max_length=6)),
            ],
        ),
    ]
