# Generated by Django 3.2.3 on 2021-06-03 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoker', models.BooleanField(blank=True, default=False)),
                ('packsSmoked', models.IntegerField(blank=True, default=0)),
                ('yearsSmoked', models.IntegerField(blank=True, default=0)),
                ('packyears', models.IntegerField(blank=True, default=0)),
                ('pregnancy', models.BooleanField(blank=True, default=False)),
                ('asthama', models.BooleanField(blank=True, default=False)),
                ('asthama_age', models.IntegerField(blank=True, default=0)),
                ('lung_disease', models.BooleanField(blank=True, default=False)),
                ('lung_disease_desc', models.CharField(max_length=50)),
                ('diabetes', models.BooleanField(blank=True, default=False)),
                ('lung_cancer', models.BooleanField(blank=True, default=False)),
                ('additional_probs', models.BooleanField(blank=True, default=False)),
                ('clinical_trials', models.BooleanField(blank=True, default=False)),
                ('atrial', models.BooleanField(blank=True, default=False)),
                ('bph', models.BooleanField(blank=True, default=False)),
                ('bph_stable', models.BooleanField(blank=True, default=False)),
                ('comments', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
