# Generated by Django 3.2.3 on 2021-06-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='additional_probs',
            new_name='antibiotics',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='asthama_age',
            new_name='ashthma_age',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='asthama',
            new_name='asthma',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='clinical_trials',
            new_name='atrial_therapy',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='pregnancy',
            new_name='clinical_trial',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='smoker',
            new_name='pregnant',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='packsSmoked',
            new_name='smoke_count',
        ),
        migrations.RemoveField(
            model_name='record',
            name='comments',
        ),
        migrations.AddField(
            model_name='record',
            name='atrial_controlled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='record',
            name='info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='info_other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='other_comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='smoked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='smoking_start_age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='smoking_stop_age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='bph_stable',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
