# Generated by Django 3.2.3 on 2021-06-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20210605_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='glaucome',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
