# Generated by Django 3.2.3 on 2021-06-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_record_glaucome'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='bp_medicine_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
