# Generated by Django 3.2.3 on 2021-06-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_record_bp_medicine_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ashthma_age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='lung_disease_desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='smoke_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='smoking_start_age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='smoking_stop_age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
